name: Swift

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-11.0

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v --enable-code-coverage
    - name: Coverage report
      uses: maxep/spm-lcov-action@0.3.0

